/** Nexora Limited Construction DB API. Deploy as a Google Apps Script web app. */
const SCHEMA={Users:['UserID','FullName','Username','Password','Role','Email','Phone','Status','CreatedDate','LastLogin','ProfileImage'],Projects:['ProjectID','ProjectName','ProjectCode','ClientName','ProjectLocation','StartDate','ExpectedEndDate','ActualEndDate','ProjectStatus','ProjectManager','TotalBudget','ContractValue','Description','CreatedBy','CreatedDate','ModifiedBy','ModifiedDate','IsDeleted'],Shops:['ShopID','ProjectID','ShopName','ShopNumber','ShopType','FloorArea_SqFt','CustomerID','Status','Notes','CreatedBy','CreatedDate','IsDeleted'],ExpenseHeads:['ExpenseHeadID','ExpenseHeadName','Category','Description','Status','CreatedBy','CreatedDate','IsDeleted'],Materials:['MaterialID','MaterialName','MaterialCode','Category','DefaultUnitID','ReorderLevel','Description','Status','CreatedBy','CreatedDate','IsDeleted'],Units:['UnitID','UnitName','UnitAbbreviation','Status','CreatedBy','CreatedDate','IsDeleted'],Suppliers:['SupplierID','SupplierName','ContactPerson','Phone','Email','Address','City','TaxID','BankName','BankAccountNo','PaymentTerms','SupplierCategory','Rating','Status','Notes','CreatedBy','CreatedDate','IsDeleted'],Customers:['CustomerID','CustomerName','ContactPerson','Phone','Email','Address','City','TaxID','CustomerType','Status','Notes','CreatedBy','CreatedDate','IsDeleted'],BudgetEntries:['BudgetID','ProjectID','ShopID','ExpenseHeadID','MaterialID','Description','UnitID','EstimatedQty','EstimatedUnitRate','EstimatedAmount','BudgetPhase','Notes','Status','ApprovedBy','ApprovedDate','CreatedBy','CreatedDate','ModifiedBy','ModifiedDate','IsDeleted'],Contracts_LPO_Invoices:['ContractID','DocumentType','DocumentNumber','ProjectID','ShopID','CustomerID','SupplierID','DocumentDate','DueDate','Subject','TotalAmount','TaxAmount','GrandTotal','AmountPaid','BalanceDue','PaymentStatus','DocumentStatus','Terms','Notes','AttachmentURL','CreatedBy','CreatedDate','ModifiedBy','ModifiedDate','IsDeleted'],ContractLineItems:['LineItemID','ContractID','ExpenseHeadID','MaterialID','Description','UnitID','Quantity','UnitRate','Amount','TaxRate','TaxAmount','TotalAmount','IsDeleted'],ActualExpenses:['ExpenseID','ProjectID','ShopID','ExpenseHeadID','MaterialID','SupplierID','ContractID','ExpenseDate','ReferenceNumber','Description','UnitID','Quantity','UnitRate','Amount','TaxAmount','TotalAmount','PaymentMethod','PaymentStatus','AmountPaid','BalanceDue','ApprovalStatus','ApprovedBy','Notes','AttachmentURL','CreatedBy','CreatedDate','ModifiedBy','ModifiedDate','IsDeleted'],Payments:['PaymentID','PaymentType','ProjectID','ContractID','ExpenseID','CustomerID','SupplierID','PaymentDate','Amount','PaymentMethod','ReferenceNumber','BankName','ChequeNumber','Description','Status','CreatedBy','CreatedDate','IsDeleted'],ActivityLog:['LogID','Timestamp','UserName','Action','Module','RecordID','Details','IPAddress'],Settings:['SettingKey','SettingValue','Description']};
const PREFIX={Users:'USR',Projects:'PRJ',Shops:'SHP',ExpenseHeads:'EXH',Materials:'MAT',Units:'UNT',Suppliers:'SUP',Customers:'CUS',BudgetEntries:'BUD',Contracts_LPO_Invoices:'CON',ContractLineItems:'CLI',ActualExpenses:'EXP',Payments:'PAY',ActivityLog:'LOG'};
function out(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
function doGet(e){try{return out(route(e.parameter||{}))}catch(x){return out({success:false,error:x.message})}}
function doPost(e){try{const p=JSON.parse(e.postData.contents||'{}');return out(route(p))}catch(x){return out({success:false,error:x.message})}}
function route(p){if(p.action==='login')return login(p.username,p.password);if(p.action!=='login'&&!validateToken(p.token))throw Error('Session expired or invalid token');const a=p.action;const m={getRecords:()=>getRecords(p.sheetName,p.filters),getRecordById:()=>getRecordById(p.sheetName,p.id),searchRecords:()=>searchRecords(p.sheetName,p.searchTerm),create:()=>addRecord(p.sheetName,p.record),update:()=>updateRecord(p.sheetName,p.id,p.record),delete:()=>deleteRecord(p.sheetName,p.id),getDashboardData:getDashboardData,getDashboardSummary:getDashboardData,getBudgetVsActual:()=>getBudgetVsActual(p.projectId),getProjectProfitability:()=>getProjectProfitability(p.projectId),getProjectPnL:()=>getProjectPnL(p.projectId),getExpenseAnalysis:()=>getExpenseAnalysis(p.projectId,p.groupBy||'ExpenseHeadID'),getOverBudgetItems:()=>getOverBudgetItems(p.projectId)};if(!m[a])throw Error('Unknown action: '+a);return {success:true,data:m[a](),lastModified:new Date().toISOString()}}
function book(){return SpreadsheetApp.getActiveSpreadsheet()}
function sheet(n){const s=book().getSheetByName(n);if(!s)throw Error('Missing sheet: '+n);return s}
function setupDatabase(){Object.keys(SCHEMA).forEach(n=>{let s=book().getSheetByName(n)||book().insertSheet(n);s.clear();s.getRange(1,1,1,SCHEMA[n].length).setValues([SCHEMA[n]]);s.setFrozenRows(1);s.getRange(1,1,1,SCHEMA[n].length).setFontWeight('bold').setBackground('#172a4d').setFontColor('#ffffff')});const u=sheet('Users');[['USR-001','Prashant Khatri','prashant',hash('Nexora@2025'),'Admin','','','Active',new Date(),'',''],['USR-002','Shakeel Patel','shakeel',hash('Nexora@2025'),'Admin','','','Active',new Date(),'',''],['USR-003','Bhavik Tankaria','bhavik',hash('Nexora@2025'),'Admin','','','Active',new Date(),'',''],['USR-004','Tanjani Malima','tanjani',hash('Nexora@2025'),'Admin','','','Active',new Date(),'',''],['USR-005','Davie Chavula','davie',hash('Nexora@2025'),'Admin','','','Active',new Date(),'','']].forEach(r=>u.appendRow(r));const settings=[['CompanyName','Nexora Limited',''],['CompanyAddress','Corporate Mall, 1st Floor, Office Block B, Chilambula Road, Lilongwe, Malawi',''],['Currency','MK',''],['CurrencyName','Malawi Kwacha',''],['TaxRate','16.5',''],['TaxName','VAT',''],['FinancialYearStart','April',''],['SystemVersion','1.0.0','']];sheet('Settings').getRange(2,1,settings.length,3).setValues(settings);return 'Database ready'}
function hash(s){return Utilities.base64Encode(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,s,Utilities.Charset.UTF_8))}
function login(username,password){const rows=getRecords('Users',{}),u=rows.find(x=>String(x.Username).toLowerCase()===String(username).toLowerCase()&&x.Status==='Active');if(!u||u.Password!==hash(password))throw Error('Invalid username or password');const token=Utilities.base64EncodeWebSafe(JSON.stringify({u:u.Username,t:Date.now(),sig:hash(u.Username+password)}));const s=sheet('Users'),ids=s.getRange(2,1,s.getLastRow()-1,1).getValues();const i=ids.findIndex(x=>x[0]===u.UserID);if(i>=0)s.getRange(i+2,10).setValue(new Date());logActivity(u.Username,'Login','Users',u.UserID,'Successful login');return {success:true,data:{token:token,username:u.Username,fullname:u.FullName,role:u.Role}}}
function validateToken(t){try{const x=JSON.parse(Utilities.newBlob(Utilities.base64DecodeWebSafe(t)).getDataAsString());return !!x.u&&Date.now()-x.t<28800000}catch(e){return false}}
function values(n){const s=sheet(n),v=s.getDataRange().getValues();return v.slice(1).map(r=>Object.fromEntries(SCHEMA[n].map((h,i)=>[h,r[i]]))).filter(r=>String(r.IsDeleted).toUpperCase()!=='TRUE')}
function getRecords(n,f){let a=values(n);Object.keys(f||{}).forEach(k=>{if(f[k]!==''&&f[k]!=null)a=a.filter(r=>String(r[k]||'').toLowerCase().includes(String(f[k]).toLowerCase()))});return a}
function getRecordById(n,id){return getRecords(n,{}).find(r=>Object.values(r)[0]===id)||null}
function searchRecords(n,q){return values(n).filter(r=>Object.values(r).join(' ').toLowerCase().includes(String(q||'').toLowerCase()))}
function getNextId(n,p){const raw=sheet(n).getDataRange().getValues().slice(1);const nums=raw.map(r=>parseInt(String(r[0]).split('-')[1],10)||0);return p+'-'+String(Math.max(0,...nums)+1).padStart(3,'0')}
function duplicate(n,d,exclude){const a=values(n),idKey=SCHEMA[n][0];if(n==='Projects')return a.some(r=>r.ProjectName===d.ProjectName&&r[idKey]!==exclude);if(n==='Contracts_LPO_Invoices')return a.some(r=>r.DocumentNumber===d.DocumentNumber&&r[idKey]!==exclude);if(n==='Materials')return a.some(r=>r.MaterialName===d.MaterialName&&r[idKey]!==exclude);if(n==='Suppliers')return a.some(r=>r.SupplierName===d.SupplierName&&r.Phone===d.Phone&&r[idKey]!==exclude);return false}
function addRecord(n,d){if(!SCHEMA[n])throw Error('Invalid sheet');if(duplicate(n,d))throw Error('Duplicate record: key value already exists');const id=getNextId(n,PREFIX[n]||'REC');const row=SCHEMA[n].map(h=>h===SCHEMA[n][0]?id:h==='CreatedDate'?new Date():h==='IsDeleted'?false:d[h]??'');const l=LockService.getScriptLock();l.waitLock(10000);try{sheet(n).appendRow(row)}finally{l.releaseLock()}const user=d.CreatedBy||'system';logActivity(user,'Create',n,id,'Created record');return getRecordById(n,id)}
function updateRecord(n,id,d){const s=sheet(n),all=s.getDataRange().getValues(),idx=all.findIndex(r=>r[0]===id);if(idx<1)throw Error('Record not found');if(duplicate(n,d,id))throw Error('Duplicate record');const row=SCHEMA[n].map((h,i)=>d[h]!==undefined?d[h]:all[idx][i]);if(SCHEMA[n].includes('ModifiedDate')){row[SCHEMA[n].indexOf('ModifiedDate')]=new Date();row[SCHEMA[n].indexOf('ModifiedBy')]=d.ModifiedBy||'system'}s.getRange(idx+1,1,1,row.length).setValues([row]);logActivity(d.ModifiedBy||'system','Update',n,id,'Updated record');return getRecordById(n,id)}
function deleteRecord(n,id){return updateRecord(n,id,{IsDeleted:true,ModifiedBy:'system'})}
function logActivity(user,action,module,id,details){const s=sheet('ActivityLog');s.appendRow([getNextId('ActivityLog','LOG'),new Date(),user,action,module,id,details,''])}
function nums(n,k){return values(n).reduce((a,r)=>a+Number(r[k]||0),0)}
function getDashboardData(){const p=getRecords('Projects',{}),b=nums('BudgetEntries','EstimatedAmount'),e=nums('ActualExpenses','TotalAmount');return {kpis:{projects:p.length,active:p.filter(x=>x.ProjectStatus==='In Progress').length,budget:b,spent:e,profit:nums('Contracts_LPO_Invoices','GrandTotal')-e,pending:values('ActualExpenses').filter(x=>x.PaymentStatus!=='Paid').reduce((a,x)=>a+Number(x.TotalAmount||0),0)},projects:p,alerts:getOverBudgetItems()}}
function getBudgetVsActual(pid){const b=getRecords('BudgetEntries',{ProjectID:pid}),e=getRecords('ActualExpenses',{ProjectID:pid});const ids=[...new Set(b.map(x=>x.ExpenseHeadID).concat(e.map(x=>x.ExpenseHeadID)))];return ids.map(id=>{const budget=b.filter(x=>x.ExpenseHeadID===id).reduce((a,x)=>a+Number(x.EstimatedAmount||0),0),actual=e.filter(x=>x.ExpenseHeadID===id).reduce((a,x)=>a+Number(x.TotalAmount||0),0);return {ExpenseHeadID:id,budget:budget,actual:actual,variance:budget-actual}})}
function getProjectProfitability(pid){const p=getRecordById('Projects',pid),actual=getRecords('ActualExpenses',{ProjectID:pid}).reduce((a,x)=>a+Number(x.TotalAmount||0),0),revenue=Number(p&&p.ContractValue||0);return {project:p,revenue:revenue,cost:actual,profit:revenue-actual,margin:revenue?(revenue-actual)/revenue*100:0}}
function getProjectPnL(pid){const x=getProjectProfitability(pid);return {revenue:x.revenue,cost:x.cost,profit:x.profit,margin:x.margin,byHead:getExpenseAnalysis(pid,'ExpenseHeadID')}}
function getExpenseAnalysis(pid,g){const rows=getRecords('ActualExpenses',{ProjectID:pid}),o={};rows.forEach(r=>{const k=r[g]||'Uncategorised';o[k]=(o[k]||0)+Number(r.TotalAmount||0)});return o}
function getOverBudgetItems(pid){return getBudgetVsActual(pid).filter(x=>x.actual>x.budget)}
function getCashFlowReport(pid,from,to){return values('Payments').filter(x=>(!pid||x.ProjectID===pid)&&(!from||x.PaymentDate>=from)&&(!to||x.PaymentDate<=to))}
function getSupplierLedger(id){return values('ActualExpenses').filter(x=>x.SupplierID===id).concat(values('Payments').filter(x=>x.SupplierID===id))}
function getCustomerLedger(id){return values('Contracts_LPO_Invoices').filter(x=>x.CustomerID===id).concat(values('Payments').filter(x=>x.CustomerID===id))}
function addProject(d){return addRecord('Projects',d)}function addBudgetEntry(d){return addRecord('BudgetEntries',d)}function addContract(d){return addRecord('Contracts_LPO_Invoices',d)}function addExpense(d){return addRecord('ActualExpenses',d)}function addPayment(d){return addRecord('Payments',d)}
