#!/bin/bash
# Telcoin Association Marketing Agency — Session Start Hook
# Runs every time a Claude Code session opens in this repo.
# Sets up the daily context so the agency is ready to work immediately.

set -euo pipefail

TODAY=$(date +%Y-%m-%d)
EXEC_DIR="$CLAUDE_PROJECT_DIR/campaign/execution/$TODAY"
BRANCH="claude/campaign-iLgt5"

# Ensure we're on the right branch
cd "$CLAUDE_PROJECT_DIR"
CURRENT_BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
if [ "$CURRENT_BRANCH" != "$BRANCH" ]; then
  git checkout "$BRANCH" 2>/dev/null || true
fi

# Create today's execution folder
mkdir -p "$EXEC_DIR"
mkdir -p "$CLAUDE_PROJECT_DIR/design/output"
mkdir -p "$CLAUDE_PROJECT_DIR/campaign/research"

# Write a session context file Claude will pick up
cat > "$EXEC_DIR/SESSION-CONTEXT.md" << EOF
# Session Context — $TODAY
Auto-generated by session-start hook at $(date)

## Today's Date
$TODAY

## Active Branch
$BRANCH

## Recent Activity (last 5 commits)
$(git log --oneline -5 2>/dev/null || echo "No git history available")

## Files Produced Recently (last 48h)
$(find "$CLAUDE_PROJECT_DIR/campaign/execution" -name "*.md" -newer "$CLAUDE_PROJECT_DIR/CLAUDE.md" 2>/dev/null | head -20 || echo "None found")

## Upcoming Triggers (from research file)
$(grep -A 1 "Mar 12\|Mar 18\|April\|Late March" "$CLAUDE_PROJECT_DIR/campaign/research/TELCOIN-RESEARCH.md" 2>/dev/null | head -20 || echo "Check TELCOIN-RESEARCH.md section 7")

## Intel Files from Previous Sessions
$(ls "$CLAUDE_PROJECT_DIR/campaign/research/intel-"*.md 2>/dev/null | tail -6 || echo "None yet — Phase 0 will generate today's intel")

## YouTube Channel
https://www.youtube.com/@TelcoinTAO — check for new streams/videos every session

## X Social Listening
Search: \$TEL, Telcoin, @telcoinTAO, Telcoin Network, eUSD Telcoin

## Instruction
Read CLAUDE.md, campaign/AGENCY-MEMORY.md, and this file.
Then follow scripts/daily-agency-run.md — start with Phase 0 (Intelligence Sweep) immediately.
Phase 0 runs 3 Trend Researcher agents in parallel before anything else.
EOF

echo "Agency session started for $TODAY. Context written to $EXEC_DIR/SESSION-CONTEXT.md"
