#!/usr/bin/env bash
#
# publish-marketplace.sh — publish the freshly generated plugin marketplace to
# the `plugins` dist branch (source/dist split).
#
# The source branch (main) NEVER commits plugins/ or .claude-plugin/
# marketplace.json — they are generated output. This script:
#   1. Builds the marketplace into a temp dir (scripts/build-marketplace.py).
#   2. Validates a fresh build with scripts/check-plugin-marketplace.sh so a
#      publish can never ship a corrupt or out-of-sync tree.
#   3. Commits exactly the generated artifacts — .claude-plugin/marketplace.json
#      and plugins/<division>/** — to the `plugins` branch, replacing that
#      branch's whole tree so the committed dist exactly mirrors the source.
#   4. Pushes the `plugins` branch to `<remote>` (default: origin).
#
# Consumers point @agentPlugins at <owner>/agency-agents#plugins (VS Code) or
# `/plugin marketplace add` (Claude Code). Because `version` is omitted from
# every manifest, Claude Code versions each plugin by the dist commit SHA, so
# every publish is a new version — matching this repo's high-churn roster.
#
# This script runs in CI (publish-plugin-marketplace.yml) on every push to main,
# so the published dist can never drift from the roster. It may also be run
# locally by a maintainer with push access.
#
# Usage: ./scripts/publish-marketplace.sh [remote]   # default remote = origin
#   PUBLISH_BRANCH=plugins (override the dist branch name)
#
# Requires: bash 3.2+, python3, git with push access to the target remote.

set -euo pipefail
cd "$(dirname "$0")/.."

REMOTE="${1:-origin}"
BRANCH="${PUBLISH_BRANCH:-plugins}"

command -v python3 >/dev/null 2>&1 || {
  echo "ERROR: python3 is required to publish the marketplace." >&2
  exit 2
}

echo "== Building marketplace into a temp dir =="
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
python3 scripts/build-marketplace.py --out "$TMP"

echo "== Validating fresh build =="
# check-plugin-marketplace.sh validates a fresh generation inside its own temp
# dir. Because the builder is deterministic, that check validates exactly the
# tree we are about to publish (a fresh build == this build). This catches
# roster/structure corruption before it ever reaches the dist branch.
bash scripts/check-plugin-marketplace.sh

# Capture the source commit we are publishing from, before switching branches.
SOURCE_SHA="$(git rev-parse --short HEAD)"

echo "==> Updating $BRANCH branch (fresh root, replace whole tree) =="
# The dist branch is a generation mirror: on every publish we reset it to an
# orphan root containing ONLY the freshly generated marketplace, then force-push.
# Because it is force-updated and never hand-edited, there is no history to
# preserve — an orphan snapshot is the simplest, leak-proof representation.
# CI runs this on a throwaway checkout; locally it discard the current worktree,
# so only run it where a clean tree is acceptable (the workflow does exactly this).
git checkout --orphan "$BRANCH" >/dev/null 2>&1
git rm -rf . --ignore-unmatch >/dev/null 2>&1 || true
git clean -fdx >/dev/null 2>&1 || true

# Copy only the generated artifacts into the branch root.
cp -R "$TMP"/.claude-plugin .
cp -R "$TMP"/plugins ./plugins

# Keep a small README in the dist so the branch explains itself.
cat > README.md <<EOF
# agency-agents — published plugin marketplace

This branch is the **generated dist** for The Agency's plugin marketplace.

- **Source repo:** \`<owner>/agency-agents\` (branch \`main\`) — generator +
  agents; this branch is build output and should **never** be hand-edited.
- **How it's built:** \`scripts/build-marketplace.py\`, published by CI
  (\`.github/workflows/publish-plugin-marketplace.yml\`) on every push to main.
- **How to consume:** point \`chat.plugins.marketplaces\` (VS Code) at
  \`<owner>/agency-agents#plugins\`, or in Claude Code run
  \`/plugin marketplace add <owner>/agency-agents\` then
  \`/plugin install agency-<division>@agency-agents\`.

This branch is force-updated on every source push; treat it as a mirror of the
generated marketplace, not a codebase. See the source repo for documentation.
EOF

git add -A
if git diff --cached --quiet; then
  echo "==> No changes to publish (already current). =="
  exit 0
fi

git commit -q \
  -m "build(marketplace): publish generated marketplace (source: ${SOURCE_SHA})" \
  -m "Generated by scripts/publish-marketplace.sh from the source branch."

echo "==> Pushing $BRANCH to $REMOTE =="
git push --force "$REMOTE" "$BRANCH"
echo "PASSED: published marketplace to $REMOTE/$BRANCH"